# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-08 07:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='Author_description',
            new_name='author_description',
        ),
        migrations.RenameField(
            model_name='author',
            old_name='Author_name',
            new_name='author_name',
        ),
        migrations.RenameField(
            model_name='author',
            old_name='Author_photo',
            new_name='author_photo',
        ),
    ]
