# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-09 06:44
from __future__ import unicode_literals

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20161208_0811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_author',
            field=models.ForeignKey(on_delete=models.SET(main.models.get_sentinel_user), to='main.Author'),
        ),
    ]
